app = "tu-nombre-de-app"
primary_region = "iad"

[build]
dockerfile = "Dockerfile"
# Agregamos esta línea para ignorar la autodetección
ignorefile = "" 

[[services]]
protocol = "udp"
internal_port = 25565
[[services.ports]]
port = 25565
